apiVersion: v1
kind: Pod
metadata:
  name: my-redis-pod
  labels:
    env: dev
spec:
  containers:
  - name: my-redis-pod
    image: redis
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd

---

apiVersion:  v1
kind:  Pod
metadata:
  name:  my-redis-pod-2
  labels:
    env:  dev
spec:
  containers:
  - name:  my-redis-pod-2
    image:  redis

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight:  1
        preference:
          matchExpressions:
          - key:  disktype
            operator:  In
            values:
            - hdd
