apiVersion:  v1
kind:  Service
metadata:
  name:  my-cluster-ip-service
  labels:
    env:  test
spec:
  type:  ClusterIP
  selector:
    env:  test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
