apiVersion:  v1
kind:  Pod
metadata:
  name:  nginix-pod-for-config-map
  labels:
    env:  dev
spec:
  containers:
  - name:  my-nginix-pod
    image:  nginx
    ports:
      - containerPort:  80  
    envFrom:
      - configMapRef:
          name:  my-config
