apiVersion:  apps/v1
kind:  DaemonSet
metadata:
  name:  my-daemon-set
  labels:
    env:  dev
spec:
  template:
    metadata:  
      name:  nginx
      labels:
        env:  dev
    spec:
      containers:
      - image:  nginx
        name:  nginx
        ports:
        - containerPort:  80
  selector:
    matchLabels:
      env:  dev
