apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  dinesh-nginx-deployment
  labels:
    type:  test
spec:
  replicas:  3
  selector:
    matchLabels:
      env:  dev
  template:
    metadata:
      name:  nginx-pod
      labels:
        env:  dev
    spec:
      containers:
      - name:  nginx-dev-pod
        image:  nginx
        ports:
        - containerPort:  80
