apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp-pod
  labels:
    env: dev
spec:
  containers:
  - name: liveness-tcp-container
    image: goproxy/goproxy
    ports:
    - containerPort: 3000
    livenessProbe:
      tcpSocket:
        port: 3000
      initialDelaySeconds: 10
      periodSeconds: 5

