apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-app-deployment
  labels:  
    type: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: [ "sh", "-c" ]
        args: [ "until nslookup myservice.default.svc.cluster.local; do echo 'waiting for service to be up'; sleep 2; done" ]
      
      containers:
      - name: multi-app-container
        image: nginx
        command: [ "sh", "-c", "echo app is up and running && sleep 3600" ]
        ports:
        - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    env: dev
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80
  selector:
    env: dev

