apiVersion:  v1
kind:  Service
metadata:
  name:  my-custom-service
  labels:
    env:  dev
spec:
  type:  NodePort
  ports:
  - nodePort:  30001
    port:  80
    targetPort:  80
  selector:                        #here we are matching selector with deployment label that is present in deployment.yaml
    env:  dev
