apiVersion:  v1
kind:  Pod
metadata:
  name:  my-nginx-pod
  labels:
    env:  dev
spec:
  containers:
  - name:  my-nginx-container
    image:  nginx
    ports:
      - containerPort:  80
  tolerations:
  - key:  "gpu"
    value:  "true"
    effect:  "NoSchedule"
